name: Code Build and Review 

on: push 

jobs:
  buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the current repository on the runner
        uses: actions/checkout@v4

      - name: Setup Java 17 and Maven 
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Review the code using SonarCloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=mukeshkumar845-sonar-demo -Dsonar.organization=MukeshKumar845 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
